### ISSUE TITLE
Spigot 1.10.2 not working :(

### ISSUE THREAD

**Issue by foxi69** [Ste3et/furniture#48]
![kép](https://user-images.githubusercontent.com/2604798/82372436-4a07ac00-9a1c-11ea-806a-7b7530a07b30.png)
```
[22:00:44] [Server thread/INFO]: foxi69 issued server command: /furniture
[22:00:46] [Server thread/INFO]: foxi69 issued server command: /furniture list
[22:00:46] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'furniture' in plugin FurnitureLib v2.2.5
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-455072c-43ab266]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-455072c-43ab266]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:647) ~[spigot.jar:git-Spigot-455072c-43ab266]
	at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1351) [spigot.jar:git-Spigot-455072c-43ab266]
	at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1186) [spigot.jar:git-Spigot-455072c-43ab266]
	at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-455072c-43ab266]
	at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-455072c-43ab266]
	at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-455072c-43ab266]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_251]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_251]
	at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot.jar:git-Spigot-455072c-43ab266]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732) [spigot.jar:git-Spigot-455072c-43ab266]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-Spigot-455072c-43ab266]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigot.jar:git-Spigot-455072c-43ab266]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot.jar:git-Spigot-455072c-43ab266]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
Caused by: java.lang.NoSuchMethodError: net.md_5.bungee.api.chat.ComponentBuilder.append([Lnet/md_5/bungee/api/chat/BaseComponent;Lnet/md_5/bungee/api/chat/ComponentBuilder$FormatRetention;)Lnet/md_5/bungee/api/chat/ComponentBuilder;
	at de.Ste3et_C0st.FurnitureLib.Command.listCommand.lambda$execute$15(listCommand.java:182) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:1.8.0_251]
	at java.util.stream.SliceOps$1$1.accept(Unknown Source) ~[?:1.8.0_251]
	at java.util.stream.SortedOps$SizedRefSortingSink.end(Unknown Source) ~[?:1.8.0_251]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source) ~[?:1.8.0_251]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_251]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_251]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:1.8.0_251]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:1.8.0_251]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_251]
	at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:1.8.0_251]
	at de.Ste3et_C0st.FurnitureLib.Command.listCommand.execute(listCommand.java:162) ~[?:?]
	at de.Ste3et_C0st.FurnitureLib.Command.command.onCommand(command.java:147) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-455072c-43ab266]
	... 15 more
```

Spigot 1.10.2
DiceFurniture Plugin / Möbel Plugin 3.4.4
FurnitureLibary/ProtectionLib 2.2.5

**Comment by ghost** [comment]
It has something to do with BungeeCord

**Comment by foxi69** [comment]
i am not using BungeeCord

**Comment by Ste3et** [comment]
hase been fixed at https://github.com/Ste3et/FurnitureLib/commit/274742ee309165af10282316535dd830380c30f1 use the newest dev version -> https://dicecraft.de/furniture/download.php?plugin=FurnitureLib&build=DevBuild&version=Spigot%201.9.x%20-%201.15.x&buildNummer=153585766

**Comment by foxi69** [comment]
@Ste3et 

**Not working as player:**

```
[20:51:44] [Server thread/INFO]: foxi69 issued server command: /furniture
[20:51:44] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'furniture' in plugin FurnitureLib v2.2.7
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[craftbukkit.jar:git-Spigot-455072c-43ab266]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[craftbukkit.jar:git-Spigot-455072c-43ab266]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:647) ~[craftbukkit.jar:git-Spigot-455072c-43ab266]
	at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1351) [craftbukkit.jar:git-Spigot-455072c-43ab266]
	at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1186) [craftbukkit.jar:git-Spigot-455072c-43ab266]
	at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [craftbukkit.jar:git-Spigot-455072c-43ab266]
	at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [craftbukkit.jar:git-Spigot-455072c-43ab266]
	at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit.jar:git-Spigot-455072c-43ab266]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_251]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_251]
	at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [craftbukkit.jar:git-Spigot-455072c-43ab266]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732) [craftbukkit.jar:git-Spigot-455072c-43ab266]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [craftbukkit.jar:git-Spigot-455072c-43ab266]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [craftbukkit.jar:git-Spigot-455072c-43ab266]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [craftbukkit.jar:git-Spigot-455072c-43ab266]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
Caused by: java.lang.NoSuchMethodError: org.bukkit.command.CommandSender.spigot()Lorg/bukkit/command/CommandSender$Spigot;
	at de.Ste3et_C0st.FurnitureLib.Command.command.sendHelp(command.java:173) ~[?:?]
	at de.Ste3et_C0st.FurnitureLib.Command.command.onCommand(command.java:152) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[craftbukkit.jar:git-Spigot-455072c-43ab266]
	... 15 more
```
```
[20:51:51] [Server thread/INFO]: foxi69 issued server command: /furniture list
[20:51:51] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'furniture' in plugin FurnitureLib v2.2.7
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[craftbukkit.jar:git-Spigot-455072c-43ab266]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[craftbukkit.jar:git-Spigot-455072c-43ab266]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:647) ~[craftbukkit.jar:git-Spigot-455072c-43ab266]
	at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1351) [craftbukkit.jar:git-Spigot-455072c-43ab266]
	at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1186) [craftbukkit.jar:git-Spigot-455072c-43ab266]
	at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [craftbukkit.jar:git-Spigot-455072c-43ab266]
	at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [craftbukkit.jar:git-Spigot-455072c-43ab266]
	at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit.jar:git-Spigot-455072c-43ab266]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_251]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_251]
	at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [craftbukkit.jar:git-Spigot-455072c-43ab266]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732) [craftbukkit.jar:git-Spigot-455072c-43ab266]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [craftbukkit.jar:git-Spigot-455072c-43ab266]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [craftbukkit.jar:git-Spigot-455072c-43ab266]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [craftbukkit.jar:git-Spigot-455072c-43ab266]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
Caused by: java.lang.NoSuchMethodError: org.bukkit.command.CommandSender.spigot()Lorg/bukkit/command/CommandSender$Spigot;
	at de.Ste3et_C0st.FurnitureLib.Command.objectToSide.<init>(objectToSide.java:130) ~[?:?]
	at de.Ste3et_C0st.FurnitureLib.Command.listCommand.execute(listCommand.java:222) ~[?:?]
	at de.Ste3et_C0st.FurnitureLib.Command.command.onCommand(command.java:148) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[craftbukkit.jar:git-Spigot-455072c-43ab266]
	... 15 more
```

**In console working:**

```
[20:52:03] [Server thread/INFO]: +--------------------------------------------+[01/03]
[20:52:03] [Server thread/INFO]:  - Adventi naptár [give] [recipe] [remove] [?]
[20:52:03] [Server thread/INFO]:  - Catapult [give] [recipe] [remove] [?]
[20:52:03] [Server thread/INFO]:  - Csontváz [give] [recipe] [remove] [?]
[20:52:03] [Server thread/INFO]:  - Cukorka [give] [recipe] [remove] [?]
[20:52:03] [Server thread/INFO]:  - Farönk [give] [recipe] [remove] [?]
[20:52:03] [Server thread/INFO]:  - Fegyvertartó [give] [recipe] [remove] [?]
[20:52:03] [Server thread/INFO]:  - Fekete tábla [give] [recipe] [remove] [?]
[20:52:03] [Server thread/INFO]:  - Függőágy [give] [recipe] [remove] [?]
[20:52:03] [Server thread/INFO]:  - Guillotine [give] [recipe] [remove] [?]
[20:52:03] [Server thread/INFO]:  - Gyertya [give] [recipe] [remove] [?]
[20:52:03] [Server thread/INFO]:  - Hirdetőtábla [give] [recipe] [remove] [?]
[20:52:03] [Server thread/INFO]:  - Hordó [give] [recipe] [remove] [?]
[20:52:03] [Server thread/INFO]:  - Hálózsák [give] [recipe] [remove] [?]
[20:52:03] [Server thread/INFO]:  - Hóember [give] [recipe] [remove] [?]
[20:52:03] [Server thread/INFO]:  - Iskolai asztal [give] [recipe] [remove] [?]
[20:52:03] [Server thread/INFO]: +--------------------------------------------+[«/»
```

btw /furniture was works before this update :(

**Comment by foxi69** [comment]
https://dicecraft.de/furniture/dump.php?id=r5gVJWgpOtzX1l0XjmpKuvdkpCncep5b

**Comment by Ste3et** [comment]
Please try these devBuild https://dicecraft.de/furniture/download.php?plugin=FurnitureLib&build=DevBuild&version=Spigot%201.9.x%20-%201.15.x&buildNummer=155748635 i hope the commit fix it https://github.com/Ste3et/FurnitureLib/commit/fd016ea6df864df72c142639dd9c4ea04a39bcf3

**Comment by foxi69** [comment]
seems like works fine :D

but if i use "/furniture toggle foxi69" command it will duplicate message
![kép](https://user-images.githubusercontent.com/2604798/84539233-59b0a280-acf3-11ea-9a3c-de69bd18b62a.png)

**Comment by Ste3et** [comment]
I think these can be closed all bugs should be fixed in the last major update
